// Inline the KB's data/ contract into a single ESM module so the app has NO runtime
// filesystem dependency — the same bundle runs on Node (local) and Cloudflare Workers (prod).
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const kbRoot = join(appRoot, "..");
const dataDir = join(kbRoot, "data");

function loadDir(name) {
  const dir = join(dataDir, name);
  return readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .map((f) => JSON.parse(readFileSync(join(dir, f), "utf8")));
}

const exercises = loadDir("exercises");
const muscles = loadDir("muscles");
const programs = loadDir("programs");
const contraindications = JSON.parse(readFileSync(join(dataDir, "injury-contraindications.json"), "utf8"));

mkdirSync(join(appRoot, "src"), { recursive: true });
const out = join(appRoot, "src", "kb-data.mjs");
const body =
  `// AUTO-GENERATED by scripts/gen-kb-data.mjs — do not edit. Run \`npm run build-data\`.\n` +
  `export const exercises = ${JSON.stringify(exercises)};\n` +
  `export const muscles = ${JSON.stringify(muscles)};\n` +
  `export const programs = ${JSON.stringify(programs)};\n` +
  `export const contraindications = ${JSON.stringify(contraindications)};\n`;
writeFileSync(out, body);
console.log(`Wrote src/kb-data.mjs — ${exercises.length} exercises, ${muscles.length} muscles, ${programs.length} programs, contraindications.`);
